name: Create Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Download artifact from commit that got tagged
        uses: dawidd6/action-download-artifact@v12
        with:
          workflow: build_and_test.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: Release
          path: ./Release/
          if_no_artifact_found: fail

      - run: ./tools/setup.ps1
        shell: pwsh

      - run: Invoke-Build -Task ShowDebugInfo -VersionToPublish ${{ github.ref_name }}
        shell: pwsh

      - run: Invoke-Build -Task Publish -VersionToPublish ${{ github.ref_name }} -PSGalleryAPIKey ${{ secrets.PSGalleryAPIKey }}
        shell: pwsh

      - name: Cherry pick CHANGELOG.md
        id: changelog
        uses: MatteoCampinoti94/changelog-to-release@v1.0.6
        with:
          version-name: ${{ github.ref_name }}
          configuration: ./.github/changelog.configuration.json
        if: ${{ hashFiles('CHANGELOG.md') != '' }}

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.body }}
          files: ./Release/JiraPS.zip
          fail_on_unmatched_files: true
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
